### PR TITLE
Issue#41 changing models plot.py

### PR DESCRIPTION
**Pull request by topape**

### CODE REVIEW

**Comment by ahaselsteiner** [comment]
@topape and @janlehmk  I resolved the merge conflicts. The tests are running. However, the plots are not correct yet.
I took our sample file and fitted the Vanem2012 model to it and got these results: https://s3.eu-central-1.amazonaws.com/virocon-media-dev/ViroCon_PlotFit.pdf

Did you have this working properly and it got broken during the merging or did you not implement this correctly? Please have a look at it.

**Comment by topape** [comment]
solved fitting-plot error. 

bildschirmfoto 2018-04-23 um 17 47 55

**Comment by ahaselsteiner** [comment]
Thanks Tobias!
There are some some things, which still should be addressed:
 * Figures should not be printed two or even three times (https://s3.eu-central-1.amazonaws.com/virocon-media-dev/ViroCon_PlotFit_04_24.pdf)
* The x-axis should be labelded with the variable name and not with the variable symbol
* This pull request now merges into an old commit of master, please make a pull request to the head of master
* Issue#129 is not solved by this pull request, did you try this? This is a screenshot showing the problem occurs also at this feature-branch: 
image
However, this is no problem, it can be addressed in an own feature branch.

**Comment by topape** [comment]
I did some changes to ease the fit error. But I am not sure if it will work because im not able to start the server.

**Comment by topape** [comment]
All requested changes are implemented. I recommend to merge this branch into the master branch.

**Pull request merged**
