### PR TITLE
issue#70-consistent-titles-2

### PR DESCRIPTION
**Pull request by topape**
uppercase titles
 removed logo, 
consistent page-header 

bildschirmfoto 2018-02-28 um 18 52 21
 It isn't possible to capitalize the highlighted titles in the images.  The user sets the title of the variable names.

### CODE REVIEW

**Comment by topape** [comment]
test failed. I 'll fix it

**Comment by ahaselsteiner** [comment]
I cannot get your branch to run: I get the following error message:

image

The console shows this:

image

**Comment by ahaselsteiner** [comment]
The tests, however, work on my PC too:
image

**Comment by ahaselsteiner** [comment]
@topape Sorry, this error was due to my changed database. Your code is fine.

**Pull request merged**
